### ISSUE TITLE
在MovieLen-1m数据集上跑GRU4Rec，统计指标异常

### ISSUE THREAD

**Issue by hansonchen1996** [wubinzzu/NeuRec#10]
数据集：MovieLen-1m原始数据

Recommender：GRU4Rec

Hyperparameters:
lr=0.001
reg=0.0
layers=[100]
batch_size=256
loss=bpr
hidden_act=tanh
final_act=linear
epochs=100 

**rec.evaluate.neg=100**

统计指标：
HR@1	HR@5	HR@10	NDCG@1	NDCG@5	NDCG@10	MRR@1	MRR@5	MRR@10
epoch 0:	0.36889184	0.71459335	0.83236706	0.36889184	0.55202842	0.59043419	0.36889184	0.49796271	0.51400179

**明显高于已有文献的统计数值**，望解答

**Comment by wubinzzu** [comment]
实验结果的绝对值与该参数rec.evaluate.neg=100相关性很强，100表示采样100个负样本进行测试。改为0表示每个用户所有未交互的物品均参与测试排序。

**Comment by hansonchen1996** [comment]
是的，根据相关文献，在采样100个负样本的情况下，GRU4Rec的NDCG@10应该在0.35左右。与测试结果出入很大

**Comment by hansonchen1996** [comment]
> 实验结果的绝对值与该参数rec.evaluate.neg=100相关性很强，100表示采样100个负样本进行测试。改为0表示每个用户所有未交互的物品均参与测试排序。

您好，能给个联系方式吗，有具体问题请教
