### ISSUE TITLE
SASRec

### ISSUE THREAD

**Issue by theconsolelogger** [wubinzzu/NeuRec#14]
The SASRec model has no build_graph function.

**Expected behaviour**
For the build_graph function to be called for the SASRec class.

**Actual behaviour**
The build_graph function is not called because it does not exist in the SASRec class.

**Suggested action**
Implement the build_graph function.

![Screenshot_2019-11-06 Untitled](https://user-images.githubusercontent.com/6412722/68284520-a460a100-00b8-11ea-9573-a8ec4113bd5a.png)

**Comment by ZhongchuanSun** [comment]
This bug has been fixed, and the same bugs in Caser, GRU4Rec, GRU4RecPlus have also fixed.

**Comment by theconsolelogger** [comment]
The commit with the fix for reference: 6c718f0cf32049c8e88b05aaa390dd93859b0854
