### ISSUE TITLE
Something about Carse -- code & training speed 

### ISSUE THREAD

**Issue by zyang1580** [wubinzzu/NeuRec#17]
(1) in util/Tool.py #69 : 
`def csr_to_user_dict_bytime(time_matrix,train_matrix):` 
but, in Caser.py:
model/sequential_recommender/Caser.py line #127:
`self.user_pos_train = csr_to_user_dict_bytime(self.dataset.train_matrix, self.dataset.time_matrix)` 

the order of inputs is not correct.

(2) The GivenData.py can't be directly used for Caser.py. 

(3) The training is every slow , maybe since the negative sampling methods. Is there any method to speed up training?

(4) It would be better, giving some examples for using sequential models.  

(5) Another thing:
Dose the sequential_recommender models have been tested and could them get similar performance in orignal paper?

**Comment by ZhongchuanSun** [comment]
(1) Thank you, this bug has been revised.
(2) GivenData.py is not used and the new version of given data splitter has not completed.
(3) The speed of negative sampling methods is acceptable in my experiments. What's the size of your dataset?
(4) Thanks for your suggestion. If you have any question, please join our WeChat group by scanning the QR code in [here](https://github.com/wubinzzu/NeuRec#contributions).
(5) The sequential models have not been fully tested. We will test them recently.
