### ISSUE TITLE
uni_evaluator.py文件中的疑问

### ISSUE THREAD

**Issue by somTian** [wubinzzu/NeuRec#28]
在evaluator/backend/cpp/uni_evaluator.py 文件的第138-142行
```
# set the ranking scores of training items to -inf,
# then the training items will be sorted at the end of the ranking list.
for idx, user in enumerate(batch_users):
    train_items = self.user_pos_train[user]
    ranking_score[idx][train_items] = -np.inf
```
    
为什么需要将训练集中的产品加入到模型的评估阶段？
当测试冷启动问题时，用户训练集中无对应的产品，是否应该考虑该情况？

**Comment by ZhongchuanSun** [comment]
@somTian 这个是在测试阶段将训练集中的物品排除, 当训练集中的物品评分为-np.inf时, 排序时会将这些物品放到整个列表的最后面.

关于冷启动测试, 是我们忽略了, 需要在赋值前加一句判断的.
