### ISSUE TITLE
在框架加是否应该加入保存模型与恢复模型的模块，下次不用在训练？

### ISSUE THREAD

**Issue by qianrenjian** [wubinzzu/NeuRec#6]

**Comment by wubinzzu** [comment]
OK，thanks for your suggestions

**Comment by qianrenjian** [comment]
已收到，感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "bin wu"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 晚上8:06
收件人: "wubinzzu/NeuRec"<NeuRec@noreply.github.com&gt;; 
抄送: "寇可往，我亦可往"<825358445@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [wubinzzu/NeuRec] 在框架加是否应该加入保存模型与恢复模型的模块，下次不用在训练？ (#6)




Closed #6.
