### ISSUE TITLE
The inputs of Dataset() might be wrong in main.py

### ISSUE THREAD

**Issue by Yaoming95** [wubinzzu/NeuRec#7]
In the main.py, line 45 (https://github.com/wubinzzu/NeuRec/blob/cde68330ac95ccddd483b0b78662fe9f53e7e742/main.py#L45), it is 
`dataset = Dataset(data_input_path,dataset_name,splitter,separator,threshold,evaluate_neg,splitterRatio) `.
However, in the __init__ method of Dataset, it says 
`def __init__(self,path,dataset_name, data_format, splitter,separator,threshold,evaluate_neg,splitterRatio=[0.8,0.2])`

Possibly, an input argument `dataset_format` is missing in main.py, line 45. It should be 

`dataset = Dataset(data_input_path, dataset_name, dataset_format, splitter, separator, threshold, evaluate_neg, splitterRatio)`

**Comment by wubinzzu** [comment]
Ok, thanks for your suggestion.
